### ISSUE TITLE
Small issue: wrong link on charmhub.io for "Homepage"

### ISSUE THREAD

**Issue by mcjaeger** [canonical/postgresql-k8s-operator#296]
## Steps to reproduce

go to https://charmhub.io/postgresql-k8s

click in relevant links on "Homepage"

## Expected behavior

open https://canonical.com/data/docs/postgresql/iaas
(maybe)

## Actual behavior

https://ubuntu.com/data/postgresql
results in a 404

## Versions

[current version of the metadata.yaml](https://github.com/canonical/postgresql-k8s-operator/blob/main/metadata.yaml)

## Screenshot

<img width="1114" alt="Screenshot 2023-10-20 at 12 52 57" src="https://github.com/canonical/postgresql-k8s-operator/assets/3418977/eb29a758-0c52-421e-ac4a-22b93e8bc3f5">

**Comment by taurus-forever** [comment]
@mcjaeger  thank you for the report, we saw it. Currently charmhub.io simply shows the first link from the ['website' list](https://github.com/canonical/postgresql-k8s-operator/blob/main/metadata.yaml#L12-L16).
I do not like the idea to point directly into the documentation, I would prefer https://github.com/canonical/postgresql-k8s-operator if public page will not be released soon.

Mohamed, do we have understanding about the expected date of publishing https://ubuntu.com/data/postgresql and https://ubuntu.com/data/mysql ? Otherwise I have to revert this and re-apply later... Meh...

Tnx!
