### ISSUE TITLE
Service patch fails due to non-unique port names

### ISSUE THREAD

**Issue by natalian98** [canonical/postgresql-k8s-operator#99]
### Bug Description

When deploying postgresql-k8s edge, the following error occurs:
```
ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: Service "postgresql-k8s" is invalid: spec.ports[1].name: Duplicate value: "postgresql-k8s"
```
See exemplary integration tests failing: [postgresql-k8s CI](https://github.com/canonical/postgresql-k8s-operator/actions/runs/4248520920/jobs/7387820795#step:6:214)

As pointed by @rbarry82, the issue lies in non-unique names of the patched service ports - see [this](https://chat.charmhub.io/charmhub/pl/r3dhicii73gajbuyok7mw6ktgy) conversation.

### To Reproduce

`juju deploy postgresql-k8s --channel edge --trust`

### Environment

postgresql-k8s latest/edge rev44
juju 3.1.0
microk8s 1.25-strict/stable

### Relevant log output

```shell
unit-postgresql-k8s-0: 01:30:41 ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: Service "postgresql-k8s" is invalid: spec.ports[1].name: Duplicate value: "postgresql-k8s"
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)
```

### Additional context

Not sure how relevant it is, but I was able to deploy revision 44 without this error in [this](https://github.com/canonical/hydra-operator/actions/runs/4244140567/jobs/7377847046) run, while in [this](https://github.com/canonical/hydra-operator/actions/runs/4262690972/jobs/7418505696) one it failed. I wasn't able to relate it to any recently updated lib.

**Comment by taurus-forever** [comment]
Dear @natalian98, thank you for the bugreport!

The investigation [scheduled for the next pulse 23#6](https://warthogs.atlassian.net/browse/DPE-1378) (March 13-26)!

From my experience the  `ERROR ... Duplicate value` is not related to `ssl ... WRONG_VERSION_NUMBER`, it used to be [considered](https://warthogs.atlassian.net/browse/DPE-1127) as harmless message (to be cleaned).

Just to be on the common ground:
 * we have recently migrated to jammy in revision 46 (PostgreSQL 14!). We are not planning to support focal series (man-power + HW resources). Is it OK with you?
 * if above is OK, is your issue still reproducible on jammy revisions? The latest is 47 as for now.
 * Locally we are testing Juju 2.9 LTS only... our K8s CI/CD stuck with juju-agent 2.9.24 due to known [juju scale-down issue](https://bugs.launchpad.net/juju/+bug/1977582). I see you are testing on Juju 3.1. Might be a source of some instabilities.
 * Also we are testing on the latest/stable microk8s 1.26.1 and your env is using 1.25 (just a curiosity, what is the reason for old microk8s)?
 * I see the error about SSL version, but I see no relation with `tls-operator`, check [this](https://github.com/canonical/postgresql-k8s-operator#tls-certificates-interface). Make sure you are relating with `tls-operator` if you expect SSL on PostgreSQL side. Still charm should not crash, we will investigate this in pulse `23#6`.

Thank you for trying our charm and for the feedback!

**Comment by rbarry82** [comment]
As a side comment @taurus-forever, the scale-down issue was solved a while ago. There's a different issue around unit startup now, but it's quite recent and actively being worked on, you should be able to move up to 2.9.37 or so

**Comment by taurus-forever** [comment]
> There's a different issue around unit startup now, but it's quite recent and actively being worked on, you should be able to move up to 2.9.37 or so

Discussed with Ryan in private, [our issue](https://bugs.launchpad.net/juju/+bug/1977582)  is still topical even for 2.9.38 and pending [Pebble fix](https://github.com/canonical/pebble/pull/190).

**Comment by natalian98** [comment]
Hi @taurus-forever thanks a lot for looking at this issue.

After having a closer look it seems that the message is harmless indeed, although it would be great to remove it to avoid confusion. My problem turned out to be related to events deferring, so this issue can be closed.

To answer your questions:
- we are more than happy to have jammy support for postgres
- as explained, it was not related to model series
- when are you planning to support juju 3.0+?
- we are going to bump the microk8s version in our CI
- I sent an example of CI failing with this "error" in postgresql-k8s as I figured out it would be easier for you to debug with your own tests :) we are not using tls-operator for now.

Thanks for help!

**Comment by marceloneppel** [comment]
Hi @natalian98! The new revision of the charm fixed the error:

```
ERROR unit.postgresql-k8s/0.juju-log Kubernetes service patch failed: Service "postgresql-k8s" is invalid: spec.ports[1].name: Duplicate value: "postgresql-k8s"
```

Thanks for the bug report and for sharing the link to the Mattermost discussion.
